repos:
  # default pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # - id: check-json
    # - id: pretty-format-json
    #   args: ["--autofix"]
    # - id: check-yaml
    - id: check-ast
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: trailing-whitespace
    # Check for debugger imports and py37+ breakpoint() calls
    # in python source.
    - id: debug-statements
  # ensure code is black compliant
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
  # fetch the isort package
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  # add autoflake
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
  # run flake8 and make sure it passes
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
  # add mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: ["--show-error-codes", "--ignore-missing-imports"]
        # additional_dependencies: []
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
