
[project]
name = "kala"
version = "0.0.1"
authors = [
  { name="Rodrigo L.C.", email="rodrigolealc@ciencias.unam.mx" },
  { name="Leonardo C.G.", email="lmcastrogonzalez@turing.ac.uk"}
]
description = "Kala: agent-based econ games"
readme = "README.md"
requires-python = ">=3.10"
license =  {file = "LICENSE"}
# classifiers = [
# ]
# dynamic = ["version"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.black]
line-length = 100
target-version = ['py310']


[tool.isort]
profile = "black"


[tool.pylint]
max-line-length = 100


[tool.mypy]
ignore_missing_imports = true
